/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectakhir;

import java.awt.Image;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class BelanjaPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form BelanjaPanel
     */
    public BelanjaPanel(String produkNama, BigDecimal produkHarga, int jumlah, String gambarProduk) {
        initComponents();

        // Format the BigDecimal to currency format
        NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        String formattedHarga = format.format(produkHarga);  // Pass BigDecimal directly to format

        // Set the product name, price, and quantity in the UI
        listNamaProduk.setText(produkNama + "(" + String.valueOf(jumlah) + ")" );
        listHarga.setText(formattedHarga);
        
        // Load the original icon but wait to resize until the component has a valid size
        ImageIcon originalIcon = new ImageIcon(gambarProduk);
        listFoto.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                // Get the image and scale it to the JLabel size
                Image image = originalIcon.getImage();
                Image scaledImage = image.getScaledInstance(listFoto.getWidth(), listFoto.getHeight(), Image.SCALE_SMOOTH);
                listFoto.setIcon(new ImageIcon(scaledImage));
                // Remove the listener after resizing to avoid unnecessary events
                listFoto.removeComponentListener(this);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listFoto = new javax.swing.JLabel();
        listNamaProduk = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        listHarga = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        setLayout(new java.awt.BorderLayout(10, 0));

        listFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        listNamaProduk.setText("jLabel1");
        add(listNamaProduk, java.awt.BorderLayout.CENTER);

        listHarga.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(listHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel listFoto;
    private javax.swing.JLabel listHarga;
    private javax.swing.JLabel listNamaProduk;
    // End of variables declaration//GEN-END:variables
}
