/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectakhir;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class panelProduk extends javax.swing.JPanel {
    private int idProduk;
    private String produkNama;
    private String gambarProduk;
    private BigDecimal produkHarga;
    private ArrayList<Produk> keranjangBelanja;
    /**
     * Creates new form panelProduk
     */
    public panelProduk(int idProduk, String gambarProduk, String produkNama, String produkHarga, ArrayList<Produk> keranjangBelanja) {
        this.keranjangBelanja = keranjangBelanja;
        initComponents();
        
        this.idProduk = idProduk;
        this.produkNama = produkNama;
        
        try {
            this.gambarProduk = gambarProduk;
            // Convert the price to BigDecimal and format as Rupiah currency
            this.produkHarga  = new BigDecimal(produkHarga);
            NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            String formattedHarga = format.format(this.produkHarga);

            // Set product name and formatted price
            tProduk.setText(produkNama);
            tHarga.setText(formattedHarga);

            // Load the original icon but wait to resize until the component has a valid size
            ImageIcon originalIcon = new ImageIcon(this.gambarProduk);
            tGambar.addComponentListener(new java.awt.event.ComponentAdapter() {
                @Override
                public void componentResized(java.awt.event.ComponentEvent e) {
                    // Get the image and scale it to the JLabel size
                    Image image = originalIcon.getImage();
                    Image scaledImage = image.getScaledInstance(tGambar.getWidth(), tGambar.getHeight(), Image.SCALE_SMOOTH);
                    tGambar.setIcon(new ImageIcon(scaledImage));
                    // Remove the listener after resizing to avoid unnecessary events
                    tGambar.removeComponentListener(this);
                }
            });

        } catch (NumberFormatException e) {
            System.err.println("Invalid price format: " + produkHarga);
            tHarga.setText("Invalid price");
        } catch (Exception e) {
            e.printStackTrace();
        }
        // Menambahkan fungsi ke tombol "Add to Cart"
        btnCheckOut.addActionListener(addToCartListener);
    }
    // Fungsi Listener untuk menambahkan produk ke keranjang belanja
    private ActionListener addToCartListener = e -> {
        Produk produk = new Produk(idProduk, produkNama, produkHarga, gambarProduk);
        keranjangBelanja.add(produk);
        System.out.println(idProduk + gambarProduk + " telah ditambahkan ke keranjang.");
    };
    // Kelas Produk sederhana untuk merepresentasikan produk
    public class Produk {
        private int id;
        private String nama;
        private String gambarProduk;
        private BigDecimal harga;

        public Produk(int id, String nama, BigDecimal harga, String gambarProduk) {
            this.id = id;
            this.nama = nama;
            this.gambarProduk = gambarProduk;
            this.harga = harga;
        }

        public int getId() {
            return id;
        }
        
        public String getNama() {
            return nama;
        }
        
        public String getGambar() {
            return gambarProduk;
        }

        public BigDecimal getHarga() {
            return harga;
        }
    }
    
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        tGambar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tProduk = new javax.swing.JLabel();
        tHarga = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tGambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        tProduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tProduk.setText("nama produk");
        jPanel5.add(tProduk, java.awt.BorderLayout.PAGE_START);

        tHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tHarga.setText("harga");
        jPanel5.add(tHarga, java.awt.BorderLayout.CENTER);

        btnCheckOut.setText("Add to Cart");
        jPanel5.add(btnCheckOut, java.awt.BorderLayout.PAGE_END);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel tGambar;
    private javax.swing.JLabel tHarga;
    private javax.swing.JLabel tProduk;
    // End of variables declaration//GEN-END:variables
}
